### ISSUE TITLE
Possibility to compare multiple --project configurations in one run

### ISSUE THREAD

**Issue by StephanKuempel** [useblocks/sphinx-performance#13]
Something like:
```
sphinx-performance --project projects/p1 --project projects/p2 --pages 100 --dummies 1 --keep
```
is currently not supported.
Would be nice to have for great flexibility.
This could also make the very specific --theme option redundant.

**Comment by danwos** [comment]
Also thought about this in the past.

In the past I was against it, as (in my use cases) projects are normally totally different and are configured in a different way.

But I understand your cases, where there is only an "internal" difference (different extension version, theme fix) and the projects uses the same configuration.

Implementation should be quite easy.

**Comment by twodrops** [comment]
This would be a nice feature to have :)
