### ISSUE TITLE
Option to select Sphinx version

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinx-performance#6]
An option to select the Sphinx version would be nice.

**Comment by danwos** [comment]
This is already there: ``--sphinx``.

But it depends on the used Test project.
And currently "basic" and "needs" both support this.

``sphinx-performance --sphinx 3.2 --sphinx 4.2``

**Comment by ubmarco** [comment]
I can confirm the parameter works, however it does not show up in the help:
![image](https://user-images.githubusercontent.com/839934/154632435-be587d14-8929-43f1-9e31-61253ff906db.png)

**Comment by danwos** [comment]
Sure it does not.
It is a parameter for the test project, which can have its own defined parameters, which sphinx performance doesn't know.
The docs must be read for this.

Other missing parameters are:
* folders
* pages
* depth
* needs
* needstables
* dummies
* and much more in future
