### ISSUE TITLE
Document parameter --profile

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinx-performance#7]
The help for parameter ``--profile`` just says
```
--profile TEXT      Activates profiling for given area
```
What is meant with 'area'?

**Comment by danwos** [comment]
Argh, yeah that feature is not really available right now.

It's a copy&past result from the Sphinx-Needs performance script.
But I hope I can provide it soon.

I keep this issue open as reminder,

**Comment by danwos** [comment]
Profiling is now mostly done via ``sphinx-analysis`` command.
